package services

import (
	"context"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/freaking-codes-oss/txammp/internal/configgen"
	"github.com/freaking-codes-oss/txammp/internal/fastcgi"
	"github.com/freaking-codes-oss/txammp/internal/proc"
	"github.com/freaking-codes-oss/txammp/internal/project"
)

// PHPFPM is the PHP runtime service.
type PHPFPM struct {
	Proj *project.Project
	// Bin is the php-fpm binary.
	Bin string
	// Version is the manifest version (display fallback).
	VersionStr string
	// SendmailPath overrides php.ini sendmail_path (empty keeps PHP's
	// default).
	SendmailPath string

	proc *proc.Process
	ver  *versionProbe
}

// NewPHPFPM builds the service around project paths.
func NewPHPFPM(p *project.Project, bin, version string, sendmailPath string) *PHPFPM {
	return &PHPFPM{
		Proj:         p,
		Bin:          bin,
		VersionStr:   version,
		SendmailPath: sendmailPath,
		proc: &proc.Process{
			Name: "php",
			Bin:  bin,
			Args: []string{
				"--nodaemonize",
				"--fpm-config", p.ConfigPath("php-fpm.conf"),
			},
			Env:     []string{"PHPRC=" + p.ConfigDir()},
			LogFile: p.LogPath("php-fpm"),
			PidFile: p.PidPath("php"),
		},
		ver: newVersionProbe(bin, version, "-v"),
	}
}

func (s *PHPFPM) ID() string    { return "php" }
func (s *PHPFPM) Label() string { return "PHP-FPM" }
func (s *PHPFPM) Role() string  { return "PHP Runtime" }
func (s *PHPFPM) Endpoint() string {
	if _, err := os.Stat(s.Proj.SocketPath()); err == nil {
		return "unix:" + s.Proj.SocketPath()
	}
	return "unix (sock)"
}
func (s *PHPFPM) LogNames() []string { return []string{"php-fpm", "php-error"} }

var phpVersionRe = regexp.MustCompile(`PHP (\d+\.\d+\.\d+)`)

func (s *PHPFPM) Version() string {
	v := s.ver.String()
	if m := phpVersionRe.FindStringSubmatch(v); m != nil {
		return m[1]
	}
	return s.VersionStr
}

func (s *PHPFPM) Check(ctx context.Context) Status {
	_, running := s.proc.Running()
	if running {
		if s.ping() {
			return StatusRunning
		}
		if time.Since(s.proc.StartedAt()) < healthStartGrace {
			return StatusStarting
		}
		return StatusFailed
	}
	if _, err := os.Stat(s.Proj.PidPath("php")); err == nil {
		return StatusFailed
	}
	return StatusStopped
}

func (s *PHPFPM) ping() bool {
	pingCtx, cancel := context.WithTimeout(context.Background(), 1500*time.Millisecond)
	defer cancel()
	return fastcgi.Ping(pingCtx, s.Proj.SocketPath(), 1200*time.Millisecond) == nil
}

func (s *PHPFPM) Start(ctx context.Context) error {
	if err := writeConfig(s.Proj.ConfigPath("php-fpm.conf"), configgen.PHPFPMConf(configgen.PHPFPMOptions{
		SocketPath:  s.Proj.SocketPath(),
		PidFile:     s.Proj.PidPath("php-fpm-internal"),
		ErrorLog:    s.Proj.LogPath("php-fpm"),
		SlowLog:     s.Proj.LogPath("php-fpm-slow"),
		MaxChildren: 4,
	})); err != nil {
		return err
	}
	// php.ini is user-editable: only write when missing or when the
	// generated marker line says we own it entirely.
	ini := s.Proj.ConfigPath("php.ini")
	if !userEdited(ini) {
		if err := writeConfig(ini, configgen.PHPINI(configgen.PHPINIOptions{
			ErrorLog:     s.Proj.LogPath("php-error"),
			SessionsDir:  s.Proj.SessionsDir(),
			SendmailPath: s.SendmailPath,
		})); err != nil {
			return err
		}
	}
	return s.proc.Start()
}

func (s *PHPFPM) Stop(ctx context.Context) error {
	if err := s.proc.Stop(5 * time.Second); err != nil {
		return err
	}
	os.Remove(s.Proj.SocketPath())
	return nil
}

func (s *PHPFPM) Restart(ctx context.Context) error {
	return s.proc.Restart(5 * time.Second)
}

// userEdited reports whether a config file was customized by the user.
// php.ini is regenerated only when it still carries the generated marker.
func userEdited(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil || len(data) == 0 {
		return false
	}
	return !strings.Contains(string(data), "generated by txampp")
}
