package configgen

import (
	"strings"
	"testing"
)

func TestCaddyfileFull(t *testing.T) {
	out := Caddyfile(CaddyOptions{
		Port:        8080,
		DocRoot:     "/home/user/my site",
		PHPEnabled:  true,
		PHPSocket:   "/tmp/.stack/run/php-fpm.sock",
		Adminer:     true,
		WWWDir:      "/tmp/.stack/www",
		Mailpit:     true,
		MailpitPort: 8025,
		AccessLog:   "/tmp/.stack/logs/caddy-access.log",
		RuntimeLog:  "/tmp/.stack/logs/caddy.log",
	})

	asserts := []string{
		"admin off",
		"auto_https off",
		":8080 {",
		`root * "/home/user/my site"`, // quoted (contains space)
		"php_fastcgi unix//tmp/.stack/run/php-fpm.sock",
		"respond /__txampp/health 200",
		"@dotfiles path /.* /*/.*/**",
		"uri strip_prefix /__mailpit",
		"reverse_proxy 127.0.0.1:8025",
		"redir /__adminer /__adminer/adminer.php 308",
		"uri strip_prefix /__adminer",
		"file_server",
	}
	for _, want := range asserts {
		if !strings.Contains(out, want) {
			t.Errorf("Caddyfile missing %q\n---\n%s\n---", want, out)
		}
	}
	// Adminer handle must come before the catch-all php handler.
	if strings.Index(out, "strip_prefix /__adminer") > strings.LastIndex(out, "php_fastcgi") {
		t.Errorf("adminer handle should precede the catch-all php_fastcgi")
	}
}

func TestCaddyfileNoPHP(t *testing.T) {
	out := Caddyfile(CaddyOptions{Port: 9000, DocRoot: "/srv", AccessLog: "/l/a.log", RuntimeLog: "/l/r.log"})
	if strings.Contains(out, "php_fastcgi") {
		t.Errorf("php_fastcgi must be absent when PHP disabled")
	}
	if strings.Contains(out, "adminer") {
		t.Errorf("adminer route must be absent without PHP")
	}
	if !strings.Contains(out, ":9000 {") {
		t.Errorf("port not applied")
	}
}

func TestPHPFPMConf(t *testing.T) {
	out := PHPFPMConf(PHPFPMOptions{
		SocketPath:  "/run/php.sock",
		PidFile:     "/run/php.pid",
		ErrorLog:    "/logs/php-fpm.log",
		SlowLog:     "/logs/slow.log",
		MaxChildren: 4,
	})
	for _, want := range []string{
		"daemonize = no",
		"listen = /run/php.sock",
		"ping.path = /__fpm-ping",
		"[www]",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("php-fpm.conf missing %q", want)
		}
	}
}

func TestPHPINI(t *testing.T) {
	out := PHPINI(PHPINIOptions{
		ErrorLog:     "/logs/php-error.log",
		SessionsDir:  "/run/sessions",
		SendmailPath: "/usr/local/bin/txampp sendmail --smtp 127.0.0.1:1025",
	})
	for _, want := range []string{
		"display_errors = On",
		"error_reporting = E_ALL",
		"session.save_path = /run/sessions",
		`sendmail_path = "/usr/local/bin/txampp sendmail --smtp 127.0.0.1:1025"`,
		"generated by txampp",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("php.ini missing %q\n%s", want, out)
		}
	}
}

func TestPHPININoSendmail(t *testing.T) {
	out := PHPINI(PHPINIOptions{ErrorLog: "/l", SessionsDir: "/s"})
	if strings.Contains(out, "sendmail_path") {
		t.Errorf("sendmail_path should be absent when unset")
	}
}
