package configgen

import (
	"fmt"
	"strings"
)

// PHPFPMOptions describes the generated php-fpm.conf.
type PHPFPMOptions struct {
	SocketPath  string
	PidFile     string
	ErrorLog    string // fpm master log
	SlowLog     string
	MaxChildren int
	MaxSpare    int
}

// PHPFPMConf renders a php-fpm.conf for a single "www" pool running in
// the foreground.
func PHPFPMConf(o PHPFPMOptions) string {
	maxChildren := orDefault(o.MaxChildren, 4)
	maxSpare := orDefault(o.MaxSpare, 2)
	if maxSpare >= maxChildren {
		maxSpare = maxChildren - 1
	}
	if maxSpare < 1 {
		maxSpare = 1
	}
	var b strings.Builder
	fmt.Fprintf(&b, "; generated by txampp — do not edit (regenerated on start)\n")
	fmt.Fprintf(&b, "[global]\n")
	fmt.Fprintf(&b, "error_log = %s\n", o.ErrorLog)
	fmt.Fprintf(&b, "pid = %s\n", o.PidFile)
	fmt.Fprintf(&b, "daemonize = no\n")
	fmt.Fprintf(&b, "log_level = notice\n\n")
	fmt.Fprintf(&b, "[www]\n")
	fmt.Fprintf(&b, "listen = %s\n", o.SocketPath)
	fmt.Fprintf(&b, "listen.mode = 0660\n")
	fmt.Fprintf(&b, "pm = dynamic\n")
	fmt.Fprintf(&b, "pm.max_children = %d\n", maxChildren)
	fmt.Fprintf(&b, "pm.start_servers = 1\n")
	fmt.Fprintf(&b, "pm.min_spare_servers = 1\n")
	fmt.Fprintf(&b, "pm.max_spare_servers = %d\n", maxSpare)
	fmt.Fprintf(&b, "ping.path = /__fpm-ping\n")
	fmt.Fprintf(&b, "pm.status_path = /__fpm-status\n")
	fmt.Fprintf(&b, "slowlog = %s\n", o.SlowLog)
	fmt.Fprintf(&b, "request_slowlog_timeout = 5s\n")
	fmt.Fprintf(&b, "catch_workers_output = yes\n")
	return b.String()
}

// PHPINIOptions describes the generated php.ini.
type PHPINIOptions struct {
	ErrorLog     string
	SessionsDir  string
	SendmailPath string // empty disables the sendmail hook
	Timezone     string
}

// PHPINI renders a php.ini tuned for local development.
func PHPINI(o PHPINIOptions) string {
	tz := o.Timezone
	if tz == "" {
		tz = "UTC"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "; generated by txampp — safe to edit; regenerated on `txampp up` only when missing\n")
	fmt.Fprintf(&b, "[PHP]\n")
	fmt.Fprintf(&b, "error_reporting = E_ALL\n")
	fmt.Fprintf(&b, "display_errors = On\n")
	fmt.Fprintf(&b, "display_startup_errors = On\n")
	fmt.Fprintf(&b, "log_errors = On\n")
	fmt.Fprintf(&b, "error_log = %s\n", o.ErrorLog)
	fmt.Fprintf(&b, "memory_limit = 512M\n")
	fmt.Fprintf(&b, "upload_max_filesize = 64M\n")
	fmt.Fprintf(&b, "post_max_size = 64M\n")
	fmt.Fprintf(&b, "max_execution_time = 120\n")
	fmt.Fprintf(&b, "date.timezone = %s\n", tz)
	fmt.Fprintf(&b, "session.save_path = %s\n", o.SessionsDir)
	fmt.Fprintf(&b, "opcache.enable = 1\n")
	if o.SendmailPath != "" {
		fmt.Fprintf(&b, "sendmail_path = %s\n", phpQuote(o.SendmailPath))
	}
	fmt.Fprintf(&b, "; sqlite databases created via PDO land in .stack/data by convention\n")
	return b.String()
}

func phpQuote(s string) string {
	if strings.ContainsAny(s, " \t") {
		return "\"" + s + "\""
	}
	return s
}

func orDefault(v, def int) int {
	if v <= 0 {
		return def
	}
	return v
}
